/**
* Swagger CN
* Chuck Norri api
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param code 
 * @param type 
 * @param message 
 */
data class ApiResponse (
    val code: kotlin.Int? = null,
    val type: kotlin.String? = null,
    val message: kotlin.String? = null
) {

}

