/**
* Swagger CN
* Chuck Norri api
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param joke 
 * @param categories 
 */
data class Joke (
    val id: kotlin.Long? = null,
    val joke: kotlin.String? = null,
    val categories: kotlin.Array<kotlin.String>? = null
) {

}

